Project for module Programming in Data Analytics due date 13th December 2019

Created by Catherine A Celeste Quinlan

To create a simulated data set based on a real life phenomenon using NUMPY.RANDOM , set it in a dataframe, and use this to show the different relationships.

I chose to look at the relationship between Higher Level Junior Certificate and Leaving Certificate and variables that may influence a student's performance in Higher Level Maths.   

In [13]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb
import pandas as pd

# I import the functions I think I will be using later


In [30]:
jcert = np.random.choice(['A', 'B','C', 'D'], size=300) #  Here Im assuming that we have an equal chance of a student getting any of the grades

In [31]:
jcert

array(['D', 'D', 'C', 'D', 'D', 'C', 'D', 'A', 'C', 'B', 'C', 'B', 'B',
       'C', 'D', 'C', 'C', 'B', 'D', 'C', 'A', 'A', 'D', 'B', 'B', 'C',
       'D', 'A', 'B', 'D', 'D', 'D', 'C', 'B', 'A', 'D', 'D', 'A', 'A',
       'C', 'A', 'C', 'A', 'D', 'D', 'D', 'A', 'A', 'A', 'C', 'B', 'A',
       'D', 'C', 'D', 'D', 'B', 'B', 'C', 'D', 'C', 'A', 'C', 'C', 'C',
       'D', 'C', 'A', 'B', 'D', 'B', 'B', 'B', 'B', 'A', 'B', 'A', 'D',
       'A', 'B', 'D', 'C', 'C', 'B', 'B', 'A', 'C', 'A', 'C', 'B', 'D',
       'C', 'B', 'B', 'C', 'B', 'A', 'D', 'C', 'C', 'D', 'A', 'A', 'D',
       'B', 'D', 'A', 'D', 'B', 'C', 'A', 'D', 'B', 'B', 'C', 'C', 'B',
       'B', 'C', 'C', 'C', 'B', 'B', 'A', 'D', 'A', 'B', 'A', 'B', 'D',
       'C', 'C', 'D', 'C', 'C', 'B', 'C', 'C', 'B', 'C', 'B', 'B', 'D',
       'B', 'A', 'A', 'D', 'A', 'A', 'A', 'C', 'B', 'C', 'D', 'A', 'B',
       'C', 'D', 'C', 'A', 'D', 'B', 'B', 'B', 'A', 'D', 'B', 'B', 'D',
       'D', 'B', 'B', 'C', 'A', 'D', 'C', 'D', 'B', 'B', 'D', 'D

In [32]:
Ages = np.random.normal(18, 1, 300).round(0)
 # The majority of these students at Leaving certificate are 18.We again pick a normal distribution with a mean of 18 and a standard deviation of 1. I chose a normal distribution here as the majority of students doing the leaving has a mean of 18.I am making the assumption of a stardard deviation of 1, as some students are either 1 year above or below. 

In [33]:
Ages



array([17., 18., 18., 18., 19., 16., 17., 18., 18., 18., 17., 17., 17.,
       18., 17., 18., 18., 17., 18., 18., 18., 17., 19., 18., 18., 19.,
       19., 18., 18., 16., 18., 18., 17., 18., 18., 19., 18., 17., 17.,
       18., 18., 17., 18., 19., 18., 18., 16., 20., 20., 17., 17., 20.,
       19., 19., 18., 18., 19., 19., 19., 19., 18., 18., 19., 19., 20.,
       18., 17., 19., 17., 19., 18., 18., 18., 18., 18., 17., 18., 19.,
       18., 16., 17., 19., 18., 19., 19., 18., 17., 17., 18., 18., 19.,
       19., 19., 18., 19., 19., 18., 17., 18., 18., 18., 19., 17., 17.,
       19., 17., 19., 20., 19., 18., 17., 19., 17., 17., 19., 17., 18.,
       19., 19., 16., 18., 18., 19., 16., 19., 19., 18., 17., 18., 17.,
       18., 19., 19., 18., 19., 18., 18., 18., 18., 18., 18., 17., 18.,
       18., 18., 18., 18., 19., 17., 15., 18., 18., 17., 18., 19., 17.,
       19., 20., 18., 19., 18., 18., 20., 18., 17., 17., 19., 18., 18.,
       20., 18., 19., 18., 16., 18., 19., 19., 18., 17., 19., 18

In [34]:
# Creating an array of male and female for the 300
gender = np.random.choice(['male', 'female'], size=300)

In [35]:
gender


array(['male', 'male', 'female', 'male', 'male', 'male', 'male', 'female',
       'male', 'female', 'female', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'female', 'female', 'male', 'male',
       'male', 'female', 'male', 'female', 'female', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'female', 'male',
       'male', 'female', 'male', 'male', 'female', 'male', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'female', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'male', 'female', 'male', 'female', 'male',
       'male', 'female', 'female', 'female', 'male', 'female', 'male',
       'female', 'male', 'female', 'female', 'male', 'male', 'male',


 Leaving certificate results are linked to Junior Certificate results . Each level at leaving Certificate  having a different possibiilty and different per gender.

In [36]:
# The average  homework time per week for students in Ireland was 6 hours with a variation of 2-3 hours
hw = np.random.normal(6, 2, 300).round(0)

In [6]:
hw
#  I will decide later if I use this as some numbers appeared negative 

array([ 7.,  7.,  4.,  5.,  5.,  8.,  6.,  8.,  8.,  7.,  5.,  8.,  4.,
        6.,  5.,  5.,  7.,  4.,  6.,  7.,  4.,  9.,  4.,  9.,  8.,  5.,
        6.,  7.,  5.,  5.,  5.,  9.,  5.,  3.,  7.,  7.,  7.,  4.,  9.,
        4.,  6.,  7.,  6.,  8.,  3.,  7.,  5.,  7.,  6.,  4.,  4., 11.,
        8.,  6.,  8.,  9.,  8.,  7.,  8.,  7.,  3.,  5.,  6.,  9.,  9.,
        3.,  5.,  7.,  5.,  6.,  6.,  7., -1.,  3.,  5.,  7.,  6.,  2.,
        5.,  6.,  6.,  4.,  3.,  7.,  7.,  8.,  6.,  6.,  6.,  7.,  7.,
        7.,  7.,  8.,  7.,  3.,  9., 13.,  8.,  5.,  4., 11.,  3.,  7.,
        7.,  7.,  5.,  6.,  6., 10.,  7.,  9.,  7.,  7.,  6.,  5.,  8.,
        7.,  6.,  7.,  5.,  7.,  8.,  5.,  6., 10.,  5.,  8.,  6.,  5.,
        3.,  3.,  8., 10.,  8., 10., 10.,  6.,  3.,  2.,  6.,  7.,  3.,
        5.,  3.,  3.,  5.,  4.,  5.,  6.,  7.,  3.,  6.,  8.,  8.,  7.,
        5.,  3.,  7.,  7.,  5.,  5.,  5.,  8.,  3.,  5.,  9.,  5.,  6.,
        6.,  4.,  6.,  9.,  3.,  8.,  7.,  7.,  8., 10.,  5.,  5

In [37]:
# Real data taken from www.examinations.ie
 #    TOTAL FEMALE Higher Math Leaving cert ={332,844,150,2132,2074,1323,482,139}
  #   TOTAL MALE = Higher Math Leaving cert {766,1180,158,1963,1873,1274,496,183}
  #  jc     TOTAL FEMALE= {1743,5403,5654,3370,468,52,1}
   #     TOTAL MALE= {2112,4962,5179,3248,565,72,1}

# intialise data of lists. 
data1 = {'JC Grades 2016':["A", "B", "C", "D","E","F","NG","Total"],
        'TOTAL MALE Higher Maths Junior cert':[ 2112, 4962, 5179, 3248, 565, 72, 1,16139],
        'TOTAL FEMALE Higher Maths Junior cert':[ 1743, 5403, 5654, 3370, 468, 52, 1, 16691]} 
data2 = {'LC Grades 2019':['H1', 'H2', 'H3', 'H4','H5','H6','H7','H8','Total'],    
        'TOTAL MALE Higher Math Leaving cert':[766, 1180, 158, 1963, 1873, 1274, 496, 183,9323],
        'TOTAL FEMALE Higher Math Leaving cert':[ 332, 844, 150, 2132, 2074, 1323, 482, 139,8830]}
  

    
    # Create DataFrame
df1 = pd.DataFrame(data1) 
df2 = pd.DataFrame(data2)

def side_by_side(*objs, **kwds): # Adapted from https://stackoverflow.com/questions/35790922/how-to-render-two-pd-dataframes-in-jupyter-notebook-side-by-side
    ''' Une fonction print objects side by side '''
    from pandas.io.formats.printing import adjoin
    space = kwds.get('space', 4)
    reprs = [repr(obj).split('\n') for obj in objs]
    print(adjoin(space, *reprs))

# Print the output.
side_by_side(df1,df2)

#print(df1)
#print(df2)


  JC Grades 2016  TOTAL MALE Higher Maths Junior cert  \      LC Grades 2019  TOTAL MALE Higher Math Leaving cert  \
0              A                                 2112       0             H1                                  766   
1              B                                 4962       1             H2                                 1180   
2              C                                 5179       2             H3                                  158   
3              D                                 3248       3             H4                                 1963   
4              E                                  565       4             H5                                 1873   
5              F                                   72       5             H6                                 1274   
6             NG                                    1       6             H7                                  496   
7          Total                                16139       7   

We can see from the authentic data above that roughly half those who do Higher level at Junior Certificate do Higher for Leaving certificate. We note that for Females doing the Junior Certificate, we will assume that those with the highest levels do it for the Leaving .Then of the 8,830 females at higher LC we will deduct those at H7 and H8, so those who pass at HL in Leaving certificate would be 8209.Then tose females candidates would have come from 100% those who achieved an A(1743) at Higher level Junior Certificate. Next 6466 candidates would include those who got B (5403).Then the remaining 1o63 candidates we can assume come from the 5654 candidates who achieved C in the Junior certificate,leaving 4591 candidates who achieved C at junior not attempting/not passing higher Level.
So for females:
I will asuume 100% probability of them doing Higher Leaving Certificate if a female achieves an A or B in Junior Certificate. However,only a 1063/5654 (18.8%) chance if they achieved a C.

For males students I will work in the same manner.The 9323 Leaving candidates less those who achieved a H7 or H8.9323-679=8644.These 8644 we can assume it is made of As(2112),Bs(4962)and 1570 of those who got Cs.That is 100% of those with an A or B in Higher and 1570/5179 (30.3%) of those whose got a C.



In [14]:
# leaving Certificate results dependent on jc.
# if female and C or D then O for Ordinary level
#  if female and A or B then A-D
# if male and D then Ordinary level
# if male and ABC then A-D


Ordinary = [
  lambda x: (x['gender'] == female) and (x['jcert'] == C or D) or
   (x['gender'] == male) and (x['jcert'] == D) 
]

def group_by_condition(l, Ordinary):
    return [[item for item in l if Ordinary(item)] for Ordinary in conditions]

# [] = group_by_Ordinary( Ordinary1)



[<function __main__.<lambda>(x)>]

In [ ]:
  df['Leaving certificate'] = df.apply('jcert') (lambda 
                            , axis = 1) 
    


In [38]:
# Creating the dataframe with the simulated data \n
from pandas import DataFrame
df = pd.DataFrame({'Age 2019': Ages,'Gender': gender,'Junior Cert H Level Maths results': jcert} )
df.head()

Age 2019  Gender Junior Cert H Level Maths results
0      17.0    male                                 D
1      18.0    male                                 D
2      18.0  female                                 C
3      18.0    male                                 D
4      19.0    male                                 D

In [39]:
df['Leaving cert H Level Maths'] = df.groupby('Junior Cert H Level Maths results')['df'].transform(
    lambda x : x.x())

KeyError: 'Column not found: df'